name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install system deps
      run: |
        sudo apt update
        sudo apt install -y zip unzip openjdk-17-jdk python3-pip

    - name: Install buildozer
      run: |
        pip install --upgrade pip
        pip install buildozer cython

    - name: Build APK
      run: |
        buildozer android debug

    - name: List files (debug)
      run: |
        echo "📂 FILE LIST:"
        ls -R

    - name: Check APK exists
      run: |
        if ls bin/*.apk 1> /dev/null 2>&1; then
          echo "✅ APK FOUND"
        else
          echo "❌ NINCS APK!"
          exit 1
        fi

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: apk
        path: |
          bin/*.apk
          **/*.apk

    - name: Upload full log
      uses: actions/upload-artifact@v4
      with:
        name: buildozer-log
        path: |
          .buildozer/**/*.log
