name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk python3-pip wget

      - name: Install buildozer
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install buildozer cython

      - name: Build APK
        run: |
          set +e
          buildozer -v android debug 2>&1 | tee build_full_output.log
          code=${PIPESTATUS[0]}
          echo "===== LAST 200 LINES ====="
          tail -n 200 build_full_output.log
          echo "===== EXIT CODE: $code ====="
          exit $code

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: |
            bin/*.apk
            **/*.apk
          if-no-files-found: error

